- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs 
      state: present  

  - name: creating robshop user
    ansible.builtin.user:
      name: roboshop

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory      

  - name: Download catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip   


  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes       

  - name: install the dependencies
    ansible.builtin.command: npm install 
    args:
      chdir: /app  


  - name: copying a service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: vim /etc/systemd/system/catalogue.service

  - name: Just force systemd to reread configs (2.4 and above)
    ansible.builtin.systemd_service:
      daemon_reload: true    

  - name: copying mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo   

  - name: Install nodejs
    ansible.builtin.dnf:
      name: mongodb-org-shell 
      state: present    

  - name: load schema
    ansible.builtin.shell: mongo --host 172.31.43.114 </app/schema/catalogue.js

