- name: mongodb installation
  hosts: mongodb
  become: yes
  tasks:
  - name: copying mongodb repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb
    ansible.builtin.package:
      name: mongodb-org
      state: present

  - name: Start & Enable MongoDB Service
    ansible.builtin.service:
      name: mongod
      state: started   
      enabled: yes 

  - name: editing the ip address
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: restarting MongoDB Service
    ansible.builtin.service:
      name: mongod
      state: restarted   
      