- name: installing web
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.dnf:
      name: nginx 
      state: present
  
  - name: Recursively remove default content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: download content 
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp   

  - name: extract web application
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes    

  - name: Copy roboshop 
    ansible.builtin.copy:
      src: roboshop.conf 
      dest: /etc/nginx/default.d/roboshop.conf 

  - name: start and enable catalogue
    ansible.builtin.service:
      name: nginx
      state: restarted
      enabled: yes 
